version: '3'
services:
  hadoop-master:
    image: hadoop_master
    container_name: hadoop-master
    hostname: hadoop-master
    ports: # HOST:CONTAINER
      - "2222:2222"
      - "4040:4040"
      - "8020:8020"
      - "8088:8088"
      - "9001:9001"
      - "50070:50070"
      - "50090:50090"
    expose:
      - "8030-8050"
    networks:
      hadoop-nw:
        ipv4_address: 172.19.0.2
  hadoop-slave-1:
    image: hadoop_slave
    container_name: hadoop-slave-1
    hostname: hadoop-slave-1
    ports:
      - "8042:8042"
      - "50075:50075"
    expose:
      - "34000-48000"
      - "50010"
      - "50020"
      - "50040"
    links:
      - hadoop-master
    networks:
      hadoop-nw:
        ipv4_address: 172.19.0.3
  networks:
    hadoop-nw:
      driver: bridge
      driver_opts:
        com.docker.network.enable_ipv6: "false"
      ipam:
        driver: default
        config:
          - subnet: 172.19.0.0/16
            gateway: 172.19.0.1
